### ISSUE TITLE
Save buy meta data

### ISSUE THREAD

**Issue by annagustavsson** [hejare/jaws#125]
Table "trades"

- [x] Reference to ticker
- [x] Reference to order id ( @ alpaca)
- [x] Reference to breakouts collection (the breakout the order "belongs" to) => optional
- [x] A string ( "buy" | "sell" | "move stop loss" | "take-profit") with constant values specifying the type. When we did these actions (time)
- [x] Timestamp when buy was performed
- [x] Bought qty
- [x] Bought price

**Comment by annagustavsson** [comment]
body when posting order => {"ticker":"ETNB","orderType":"buy","price":8.32,"quantity":584}
